# This file was generated by GoReleaser. DO NOT EDIT.
class GhLabel < Formula
  desc "A tool to help you manage GitHub issue labels"
  homepage "https://github.com/erdaltsksn/gh-label"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/erdaltsksn/gh-label/releases/download/v0.5.0/gh-label_0.5.0_darwin_amd64.tar.gz"
    sha256 "63bdd4608c9ca9ba2ba0438f91cc3bc5e21dc851d0cb66a1ffc43869ffa1567b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/erdaltsksn/gh-label/releases/download/v0.5.0/gh-label_0.5.0_linux_amd64.tar.gz"
      sha256 "78ccb292ac32f94d0482f26aa05ab922ed22c263c5ad09798c6bfdf6bbc4af4f"
    end
  end

  def install
    bin.install "gh-label"
  end
end
