# This file was generated by GoReleaser. DO NOT EDIT.
class GitBump < Formula
  desc "Semantic Version Bumper using git tag"
  homepage "https://github.com/erdaltsksn/git-bump"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/erdaltsksn/git-bump/releases/download/v0.1.1/git-bump_0.1.1_darwin_amd64.tar.gz"
    sha256 "d3509bdd6650a466cf8fa86af01a93140203dc708fdf4b8978358e0e2eff7625"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/erdaltsksn/git-bump/releases/download/v0.1.1/git-bump_0.1.1_linux_amd64.tar.gz"
      sha256 "0f6a97ad6aeb8b14fc15d170d80b85993d0f107fb4d216904e0dd4155f64163a"
    end
  end

  def install
    bin.install "git-bump"
  end
end
