# This file was generated by GoReleaser. DO NOT EDIT.
class GitBump < Formula
  desc "Semantic Version Bumper using git tag"
  homepage "https://github.com/erdaltsksn/git-bump"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/erdaltsksn/git-bump/releases/download/v0.4.0/git-bump_0.4.0_darwin_amd64.tar.gz"
    sha256 "e49f6cc5670624ac0ff7dfd499225fe39dc37c7e8aa606f4f5f142b143764366"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/erdaltsksn/git-bump/releases/download/v0.4.0/git-bump_0.4.0_linux_amd64.tar.gz"
      sha256 "665c70754e545ce7692fc0173f9485dc9a0e5d76c63d0781c0798dfacd776196"
    end
  end

  def install
    bin.install "git-bump"
  end
end
