# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Random < Formula
  desc "Random data generator AKA faker"
  homepage "https://github.com/erdaltsksn/random"
  version "0.18.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erdaltsksn/random/releases/download/v0.18.1/random_0.18.1_darwin_amd64.tar.gz"
      sha256 "d67dd906732bfd56cfa42171fbab631acc358da3140cc30b331f1cbeb372ccc4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/erdaltsksn/random/releases/download/v0.18.1/random_0.18.1_linux_amd64.tar.gz"
      sha256 "f54bfd1d5d8bd766b262bb6d540a3d99c6f399ffaa14cdf34b37fcc099a0285f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdaltsksn/random/releases/download/v0.18.1/random_0.18.1_linux_arm64.tar.gz"
      sha256 "c08ea9a7bacee2f74910f85b56abe16c79a138803791aa9f883b9cbecad445f8"
    end
  end

  def install
    bin.install "random"
  end
end
