# This file was generated by GoReleaser. DO NOT EDIT.
class Random < Formula
  desc "Random data generator AKA faker"
  homepage "https://github.com/erdaltsksn/random"
  version "0.13.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/erdaltsksn/random/releases/download/v0.13.0/random_0.13.0_darwin_amd64.tar.gz"
    sha256 "86435bedd12a49711929b9f9882d1cd699a62ed9c8da87716dc7acaff8300a77"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/erdaltsksn/random/releases/download/v0.13.0/random_0.13.0_linux_amd64.tar.gz"
      sha256 "bd752297d26179004dc004068ab80c934d84fbfbd0f20fc6ae1737cbe3e31729"
    end
  end

  def install
    bin.install "random"
  end
end
